-- SQL Schema for Satgas PPKS (Nuxt + Supabase)
-- Execute this script in your Supabase SQL Editor

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Drop existing tables if they exist (for clean setup if needed)
-- drop table if exists violence_reports;
-- drop table if exists violences;
-- drop table if exists perpetrators;
-- drop table if exists reporters;
-- drop table if exists clients;
-- drop table if exists visi_misis;
-- drop table if exists tims;
-- drop table if exists edukasis;
-- drop table if exists beritas;
-- drop table if exists heroes;

-- 1. Heroes Table
create table if not exists heroes (
    id bigint generated by default as identity primary key,
    nama_gambar text not null,
    gambar text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Beritas (News) Table
create table if not exists beritas (
    id bigint generated by default as identity primary key,
    judul text not null,
    isi text not null,
    gambar text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Edukasis (Education) Table
create table if not exists edukasis (
    id bigint generated by default as identity primary key,
    judul text not null,
    konten text not null,
    gambar text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Tims (Team Members) Table
create table if not exists tims (
    id bigint generated by default as identity primary key,
    nama text not null,
    jabatan text not null,
    deskripsi text,
    foto text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Visi Misi Table
create table if not exists visi_misis (
    id bigint generated by default as identity primary key,
    about text not null,
    visi text not null,
    misi text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Clients (Korban) Table
create table if not exists clients (
    id uuid default gen_random_uuid() primary key,
    nama_lengkap text not null,
    jenis_kelamin text not null check (jenis_kelamin in ('Laki-laki', 'Perempuan')),
    status_korban text not null check (status_korban in ('Disable', 'Tidak')),
    kategori_disable text,
    status text not null, -- Mahasiswa, Dosen, Tendik, Masyarakat, etc.
    sumber_informasi text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Reporters (Pelapor) Table
create table if not exists reporters (
    id uuid default gen_random_uuid() primary key,
    hubungan_pelapor_dengan_pelaku text not null,
    nama_lengkap text not null,
    tempat_lahir text not null,
    tanggal_lahir date not null,
    jenis_kelamin text not null check (jenis_kelamin in ('Laki-laki', 'Perempuan')),
    usia integer not null,
    status_pelapor text not null,
    no_telepon text not null,
    email text not null,
    alamat text not null,
    keterangan_tambahan text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Perpetrators (Pelaku) Table
create table if not exists perpetrators (
    id uuid default gen_random_uuid() primary key,
    hubungan_dengan_korban text not null,
    nama text not null,
    telepon text,
    jenis_kelamin text not null check (jenis_kelamin in ('Laki-laki', 'Perempuan')),
    keterangan text not null,
    upload_bukti jsonb, -- Stored as JSON array of URLs/Paths
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. Violences (Kekerasan) Table
create table if not exists violences (
    id uuid default gen_random_uuid() primary key,
    jenis_kekerasan jsonb not null, -- JSON array of types, e.g. ["Seksual", "Fisik"]
    bentuk_kekerasan jsonb not null, -- JSON array of specific forms
    lokasi_kejadian text not null,
    waktu_kejadian timestamp with time zone not null,
    deskripsi_kekerasan text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Violence Reports (Laporan Utama) Table
create table if not exists violence_reports (
    id uuid default gen_random_uuid() primary key,
    id_client uuid not null references clients(id) on delete cascade,
    id_reporter uuid not null references reporters(id) on delete cascade,
    id_perpetrator uuid not null references perpetrators(id) on delete cascade,
    id_violence uuid not null references violences(id) on delete cascade,
    status text default 'terlapor' not null check (status in ('terlapor', 'diproses', 'ditolak', 'selesai')),
    code varchar(30) not null unique, -- Format: PPKS-YYYY-XXXXXXXXXX
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add indexes for better query performance
create index if not exists idx_reports_client on violence_reports(id_client);
create index if not exists idx_reports_reporter on violence_reports(id_reporter);
create index if not exists idx_reports_perpetrator on violence_reports(id_perpetrator);
create index if not exists idx_reports_violence on violence_reports(id_violence);
create index if not exists idx_reports_code on violence_reports(code);

-- Enable Row Level Security (RLS) optionally
alter table clients enable row level security;
alter table reporters enable row level security;
alter table perpetrators enable row level security;
alter table violences enable row level security;
alter table violence_reports enable row level security;
alter table beritas enable row level security;
alter table edukasis enable row level security;
alter table tims enable row level security;
alter table visi_misis enable row level security;
alter table heroes enable row level security;

-- Policies:
-- 1. Anyone can read heroes, beritas, edukasis, tims, visi_misis
create policy "Allow public read heroes" on heroes for select using (true);
create policy "Allow public read beritas" on beritas for select using (true);
create policy "Allow public read edukasis" on edukasis for select using (true);
create policy "Allow public read tims" on tims for select using (true);
create policy "Allow public read visi_misis" on visi_misis for select using (true);

-- 2. Anyone can insert client/reporter/perpetrator/violence/report (for reporting case)
create policy "Allow public insert clients" on clients for insert with check (true);
create policy "Allow public insert reporters" on reporters for insert with check (true);
create policy "Allow public insert perpetrators" on perpetrators for insert with check (true);
create policy "Allow public insert violences" on violences for insert with check (true);
create policy "Allow public insert reports" on violence_reports for insert with check (true);

-- 3. Only authenticated (admin) users can perform CRUD on content tables and full read/write on reports
create policy "Allow admin CRUD heroes" on heroes for all to authenticated using (true);
create policy "Allow admin CRUD beritas" on beritas for all to authenticated using (true);
create policy "Allow admin CRUD edukasis" on edukasis for all to authenticated using (true);
create policy "Allow admin CRUD tims" on tims for all to authenticated using (true);
create policy "Allow admin CRUD visi_misis" on visi_misis for all to authenticated using (true);

create policy "Allow admin CRUD clients" on clients for all to authenticated using (true);
create policy "Allow admin CRUD reporters" on reporters for all to authenticated using (true);
create policy "Allow admin CRUD perpetrators" on perpetrators for all to authenticated using (true);
create policy "Allow admin CRUD violences" on violences for all to authenticated using (true);
create policy "Allow admin CRUD reports" on violence_reports for all to authenticated using (true);

-- 4. Public can read a report ONLY if they know its code (used for Cek Status)
create policy "Allow public read report by code" on violence_reports for select using (true);

create policy "Allow public read client details by id" on clients for select using (true);
create policy "Allow public read reporter details by id" on reporters for select using (true);
create policy "Allow public read perpetrator details by id" on perpetrators for select using (true);
create policy "Allow public read violence details by id" on violences for select using (true);
